#ifndef SRC_PAPER_DL_BMX_GUI_DEBUG_LINUX_X64_H
#define SRC_PAPER_DL_BMX_GUI_DEBUG_LINUX_X64_H

#include <brl.mod/blitz.mod/.bmx/blitz.bmx.debug.linux.x64.h>
#include <brl.mod/event.mod/.bmx/event.bmx.debug.linux.x64.h>
#include <brl.mod/threads.mod/.bmx/threads.bmx.debug.linux.x64.h>
#include <brl.mod/io.mod/.bmx/io.bmx.debug.linux.x64.h>
#include <brl.mod/bankstream.mod/.bmx/bankstream.bmx.debug.linux.x64.h>
#include <brl.mod/eventqueue.mod/.bmx/eventqueue.bmx.debug.linux.x64.h>
#include <brl.mod/map.mod/.bmx/map.bmx.debug.linux.x64.h>
#include <brl.mod/bytebuffer.mod/.bmx/bytebuffer.bmx.debug.linux.x64.h>
#include <brl.mod/stbimageloader.mod/.bmx/stbimageloader.bmx.debug.linux.x64.h>
#include <brl.mod/d3d7max2d.mod/.bmx/d3d7max2d.bmx.debug.linux.x64.h>
#include <brl.mod/socket.mod/.bmx/socket.bmx.debug.linux.x64.h>
#include <brl.mod/openalaudio.mod/.bmx/openalaudio.bmx.debug.linux.x64.h>
#include <brl.mod/retro.mod/.bmx/retro.bmx.debug.linux.x64.h>
#include <brl.mod/clipboard.mod/.bmx/clipboard.bmx.debug.linux.x64.h>
#include <brl.mod/glgraphics.mod/.bmx/glgraphics.bmx.debug.linux.x64.h>
#include <brl.mod/freetypefont.mod/.bmx/freetypefont.bmx.debug.linux.x64.h>
#include <brl.mod/max2d.mod/.bmx/max2d.bmx.debug.linux.x64.h>
#include <brl.mod/collections.mod/.bmx/collections.bmx.debug.linux.x64.h>
#include <brl.mod/bmploader.mod/.bmx/bmploader.bmx.debug.linux.x64.h>
#include <brl.mod/stringbuilder.mod/.bmx/stringbuilder.bmx.debug.linux.x64.h>
#include <brl.mod/d3d9max2d.mod/.bmx/d3d9max2d.bmx.debug.linux.x64.h>
#include <brl.mod/timer.mod/.bmx/timer.bmx.debug.linux.x64.h>
#include <brl.mod/freeaudioaudio.mod/.bmx/freeaudioaudio.bmx.debug.linux.x64.h>
#include <brl.mod/dxgraphics.mod/.bmx/dxgraphics.bmx.debug.linux.x64.h>
#include <brl.mod/gnet.mod/.bmx/gnet.bmx.debug.linux.x64.h>
#include <brl.mod/platform.mod/.bmx/platform.bmx.debug.linux.x64.h>
#include <brl.mod/volumes.mod/.bmx/volumes.bmx.debug.linux.x64.h>
#include <brl.mod/uuid.mod/.bmx/uuid.bmx.debug.linux.x64.h>
#include <brl.mod/oggloader.mod/.bmx/oggloader.bmx.debug.linux.x64.h>
#include <brl.mod/maxlua.mod/.bmx/maxlua.bmx.debug.linux.x64.h>
#include <brl.mod/threadpool.mod/.bmx/threadpool.bmx.debug.linux.x64.h>
#include <brl.mod/jpgloader.mod/.bmx/jpgloader.bmx.debug.linux.x64.h>
#include <brl.mod/objectlist.mod/.bmx/objectlist.bmx.debug.linux.x64.h>
#include <brl.mod/wavloader.mod/.bmx/wavloader.bmx.debug.linux.x64.h>
#include <brl.mod/maxunit.mod/.bmx/maxunit.bmx.debug.linux.x64.h>
#include <brl.mod/matrix.mod/.bmx/matrix.bmx.debug.linux.x64.h>
#include <brl.mod/glmax2d.mod/.bmx/glmax2d.bmx.debug.linux.x64.h>
#include <brl.mod/pngloader.mod/.bmx/pngloader.bmx.debug.linux.x64.h>
#include <brl.mod/directsoundaudio.mod/.bmx/directsoundaudio.bmx.debug.linux.x64.h>
#include <brl.mod/base64.mod/.bmx/base64.bmx.debug.linux.x64.h>
#include <brl.mod/timerdefault.mod/.bmx/timerdefault.bmx.debug.linux.x64.h>
#include <brl.mod/tgaloader.mod/.bmx/tgaloader.bmx.debug.linux.x64.h>
#include <brl.mod/maxutil.mod/.bmx/maxutil.bmx.debug.linux.x64.h>
#include <brl.mod/randomdefault.mod/.bmx/randomdefault.bmx.debug.linux.x64.h>
#include <brl.mod/appstub.mod/.bmx/appstub.bmx.debug.linux.x64.h>
#include <brl.mod/quaternion.mod/.bmx/quaternion.bmx.debug.linux.x64.h>
#include <pub.mod/vulkan.mod/.bmx/vulkan.bmx.debug.linux.x64.h>
#include <pub.mod/win32.mod/.bmx/win32.bmx.debug.linux.x64.h>
#include <pub.mod/nfd.mod/.bmx/nfd.bmx.debug.linux.x64.h>
#include <pub.mod/freejoy.mod/.bmx/freejoy.bmx.debug.linux.x64.h>
#include <pub.mod/nx.mod/.bmx/nx.bmx.debug.linux.x64.h>
#include <pub.mod/freeprocess.mod/.bmx/freeprocess.bmx.debug.linux.x64.h>
#include <pub.mod/glad.mod/.bmx/glad.bmx.debug.linux.x64.h>
#include <pub.mod/opengles.mod/.bmx/opengles.bmx.debug.linux.x64.h>
#include <pub.mod/xmmintrin.mod/.bmx/xmmintrin.bmx.debug.linux.x64.h>
#include <pub.mod/opengles3.mod/.bmx/opengles3.bmx.debug.linux.x64.h>
int _bb_main();

#endif
